name: Statsugiri CI

on: [push]

jobs:
    formatting-linting-check:
        name: Formatting and Linting Check
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            # checks-out the repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Root Environment Setup
              run: |
                  pip install -r ./requirements.txt

            - name: Check formatting and linting
              run: |
                  ./formatting_scripts/check_formatting_ci.sh

    pytest:
        name: PS Ingestion Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            # checks-out the repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: PS Ingestion Environment Setup
              working-directory: ./src/ps_ingestion
              run: |
                  pip install -r requirements.txt

            - name: Run Pytest
              working-directory: ./src/ps_ingestion
              run: |
                  pytest .
