name: Babiri CI

on: [push]

jobs:
    formatting-linting-check:
        name: Formatting and Linting Check
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
                go-version: ["1.17.2"]
        steps:
            # checks-out the repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Set up Go ${{ matrix.go-version }}
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Environment Setup
              run: |
                  "${GITHUB_WORKSPACE}"/environment_setup/setup.sh

            - name: Check formatting and linting
              run: |
                  ./formatting_scripts/check_formatting_ci.sh

    pytest:
        name: Data Pipeline Python Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            # checks-out the repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Environment Setup
              run: |
                  "${GITHUB_WORKSPACE}"/environment_setup/setup.sh

            - name: Run Pytest
              run: |
                  make drilbur-test

    gotest:
        name: Server Go Tests
        env:
            MONGOURI: ${{ secrets.MONGOURI_CI }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: ["1.17.2"]
        steps:
            # checks-out the repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2
            - name: Set up Go ${{ matrix.go-version }}
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Environment Setup
              run: |
                  "${GITHUB_WORKSPACE}"/environment_setup/setup.sh

            - name: Run Go test
              run: |
                  make server-test
