name: Statsugiri CI on Merge

on:
    pull_request:
        types:
            - closed

jobs:
    push-ecr-images-dev:
        name: Push ECR Images
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Add SHORT_SHA env property with commit short sha
              run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

            - name: Build and push PS Ingestion image
              working-directory: ./src/ps_ingestion_lambda
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: ps-ingestion-lambda
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${SHORT_SHA} .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:${SHORT_SHA}
