name: PS Teams Service CI on Merge

on:
    pull_request:
        types: [closed]

jobs:
    push-ps-teams-service-ecr-images:
        name: Push ECR Images
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Add SHORT_SHA env property with commit short sha
              run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

            - name: Check if PS Teams Service files have changed
              id: changed-ps-teams-service-files
              uses: tj-actions/changed-files@v35
              with:
                  files: |
                      ./src/ps_teams_service/ps_teams_service_lambda/**/*.py

            - name: Build and push PS Teams Service Lambda image
              if: steps.changed-ps-teams-service-files.outputs.any_changed == 'true'
              working-directory: ./src/ps_teams_service/ps_teams_service_lambda
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: ps-teams-service-lambda
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${SHORT_SHA} .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:${SHORT_SHA}
